In [1]:
import numpy as np
import h5py
import math
import os
import pathlib
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, BatchNormalization, Activation, Layer, ReLU, LeakyReLU
from tensorflow.keras import backend as K

2021-11-05 11:38:52.169100: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0


In [2]:
from func import load_model, save_model

Restructuring data with type classification using one_hot interpretation. Loading data:

In [3]:
filename = './BKG_dataset.h5'
# make sure input data has correct input shape - background training data
with h5py.File(filename, 'r') as file:
    X_train = np.array(file['X_train'])
    X_test = np.array(file['X_test'])
    X_val = np.array(file['X_val'])

Define Dense NN architecture

In [9]:
import numpy as np
from tensorflow.keras.utils import to_categorical
### Categorical data to be converted to numeric data
colors = ["None", "MET", "electron", "muon", "jet"]

### Universal list of colors
total_colors = ["None", "MET", "electron", "muon", "jet"]

### map each color to an integer
mapping = {}
for x in range(len(total_colors)):
  mapping[total_colors[x]] = x

# integer representation
for x in range(len(colors)):
  colors[x] = mapping[colors[x]]

one_hot_encode = to_categorical(colors)
print(one_hot_encode)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Restructure data where object types as one_hot vector. Shape from [19,4] to [19,8] 


In [7]:
print(X_test[0])#orginal

[18.0988121   0.         -1.21966612 46.22872162 -1.52670538  1.81053424
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.        ]


In [33]:
bkg_file= '/home/aadi/praktika/ADC/files/background_for_training.h5'

In [34]:
events=100# mitme eventi peal treenida

In [35]:
# read BACKGROUND data
with h5py.File(bkg_file, 'r') as file:
    full_data = file['Particles'][:,:,:]
    np.random.shuffle(full_data)
    if events: full_data = full_data[:events,:,:]

In [14]:
event_obj_type=testing[:,3]#type of elements extracted

NameError: name 'testing' is not defined

In [36]:
len(full_data)

100

In [ ]:
import numpy as np
from tensorflow.keras.utils import to_categorical
### Categorical data to be converted to numeric data
colors = ["None", "MET", "electron", "muon", "jet"]

### Universal list of colors
total_colors = ["None", "MET", "electron", "muon", "jet"]

### map each color to an integer
mapping = {}
for x in range(len(total_colors)):
  mapping[total_colors[x]] = x

# integer representation
for x in range(len(colors)):
  colors[x] = mapping[colors[x]]

one_hot_encode = to_categorical(colors)
print(one_hot_encode)

Restructure data where object types as one_hot vector. Shape from [19,4] to [19,8] 


In [16]:
full_data[3] #original 19,4 shape

array([[71.04098511,  0.        , -1.0397166 ,  1.        ],
       [31.74472618, -1.58234549,  2.9478004 ,  2.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [35.29406738, -1.50310445,  1.97888601,  4.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.

In [17]:
testing=full_data[99]
print(testing)

[[31.64394569  0.          2.64225101  1.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [40.06128311 -0.72923177 -0.72488439  3.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [17.47454453 -2.05241919  1.47250724  4.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [18]:
event_obj_type=testing[:,3]#type of elements extracted
#np.transpose(data_obj_type)
print(event_obj_type)

[1. 0. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
#to onehot vector
event_obj_oh=to_categorical(event_obj_type,5)
#print(event_obj_oh)

In [20]:
event_wo_type=testing[:,:3]#event without type
#print(event_wo_type)

In [21]:
event_oh=np.concatenate((event_wo_type,event_obj_oh),axis=1)
print(event_oh.shape)
#print(event_oh)

(19, 8)


In [22]:
#suurema batchi peal
#print(full_data[:])
event_obj_type=full_data[:,:,3]
#print(event_obj_type)Object types from all events
event_obj_oh=to_categorical(event_obj_type,5)
#print(event_obj_oh[3])All the object types turned to one hot
event_wo_type=full_data[:,:,:3]#original events without type
event_oh=np.concatenate((event_wo_type[:],event_obj_oh[:]),axis=2)

In [23]:
print(event_oh[99])

[[31.64394569  0.          2.64225101  0.          1.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [40.06128311 -0.72923177 -0.72488439  0.          0.          0.
   1.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [17.47454453 -2.05241919  1.47250724  0.          0.          0.
   0.          1.        ]
 [ 0.          0.          0.          1.          0.          0.
   0

In [12]:
import argparse
import h5py
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras.utils import to_categorical

def create_datasets_dense_onehot(bkg_file, output_bkg_name, signals_files, output_signal_names, events=None, test_size=0.2, val_size=0.2, input_shape=152):

    # read BACKGROUND data
    with h5py.File(bkg_file, 'r') as file:
        full_data = file['Particles'][:,:,:]
        np.random.shuffle(full_data)
        if events: full_data = full_data[:events,:,:]

    event_obj_type=full_data[:,:,3]#Object types from all events
    event_obj_oh=to_categorical(event_obj_type,5)#All the object types turned to one hot
    event_wo_type=full_data[:,:,:3]#original events without type
    full_data=np.concatenate((event_wo_type[:],event_obj_oh[:]),axis=2)#original data combined with one hot vectors


    # define training, test and validation datasets
    X_train, X_test = train_test_split(full_data, test_size=test_size, shuffle=True)
    X_train, X_val = train_test_split(X_train, test_size=val_size)

    del full_data

    # flatten the data for model input
    X_train = X_train.reshape(X_train.shape[0], input_shape)
    X_test = X_test.reshape(X_test.shape[0], input_shape)
    X_val = X_val.reshape(X_val.shape[0], input_shape)


    with h5py.File(output_bkg_name + '_OH_dataset.h5', 'w') as h5f:
        print("saving")
        h5f.create_dataset('X_train', data = X_train)
        h5f.create_dataset('X_test', data = X_test)
        h5f.create_dataset('X_val', data = X_val)  
        
        
    if signals_files:
        # read SIGNAL data
        for i, signal_file in enumerate(signals_files):
            print("teen if")
            f = h5py.File(signal_file,'r')
            signal_data = f['Particles'][:,:,:]
            #same process as before turning types to onehot vectors
            event_obj_type=signal_data[:,:,3]#Object types from all events
            event_obj_oh=to_categorical(event_obj_type,5)#All the object types turned to one hot
            event_wo_type=signal_data[:,:,:3]#original events without type
            signal_data=np.concatenate((event_wo_type[:],event_obj_oh[:]),axis=2)#original data combined with one hot vectors
            
            signal_data = signal_data.reshape(signal_data.shape[0],input_shape)
            with h5py.File(output_signal_names[i] + '_OH_dataset.h5', 'w') as h5f2:
                h5f2.create_dataset('Data', data = signal_data)        
    return                                                                                

In [ ]:
sspython3 create_datasets_OH.py 
--bkg_file '/home/aadi/praktika/ADC/files/background_for_training.h5' 
--output_bkg_name 'BKG_OH'
--signals_files '/home/aadi/praktika/ADC/files/Ato4l_lepFilter_13TeV.h5' 
--output_signal_names 'Ato4l_lepFilter_13TeV_OH' 
--events=1000000



In [13]:
signal_files = ['/home/aadi/praktika/ADC/files/Ato4l_lepFilter_13TeV.h5',
            '/home/aadi/praktika/ADC/files/hChToTauNu_13TeV_PU20.h5',
            '/home/aadi/praktika/ADC/files/hToTauTau_13TeV_PU20.h5',
            '/home/aadi/praktika/ADC/files/leptoquark_LOWMASS_lepFilter_13TeV.h5',
            '/home/aadi/praktika/ADC/files/background_for_training.h5']


In [14]:
signal_output=['Ato4l_lepFilter_13TeV_input',
                 'hChToTauNu_13TeV_PU20_input',
                 'hToTauTau_13TeV_PU20_input',
                 'leptoquark_LOWMASS_lepFilter_13TeV_input',
                 'background_for_training_input']

In [15]:
bkg_file= '/home/aadi/praktika/ADC/files/background_for_training.h5' 
output_bkg_name= 'BKG_OH2'
signals_files= signal_files 
output_signal_names= signal_output
events=4000000

In [16]:
create_datasets_dense_onehot(bkg_file, output_bkg_name, signals_files, output_signal_names, events=None, test_size=0.2, val_size=0.2, input_shape=152)

saving
teen if
teen if
teen if
teen if
teen if
