In [170]:
import numpy as np
import h5py
import math
import os
import pathlib
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, BatchNormalization, Activation, Layer, ReLU, LeakyReLU
from tensorflow.keras import backend as K

In [171]:
from func import load_model, save_model

Restructuring data with type classification using one_hot interpretation. Loading data:

In [6]:
filename = './signals/BKG_4e6_dataset.h5'
# make sure input data has correct input shape - background training data
with h5py.File(filename, 'r') as file:
    X_train = np.array(file['X_train'])
    X_test = np.array(file['X_test'])
    X_val = np.array(file['X_val'])

Define Dense NN architecture

In [172]:
import numpy as np
from tensorflow.keras.utils import to_categorical
### Categorical data to be converted to numeric data
colors = ["None", "MET", "electron", "muon", "jet"]

### Universal list of colors
total_colors = ["None", "MET", "electron", "muon", "jet"]

### map each color to an integer
mapping = {}
for x in range(len(total_colors)):
  mapping[total_colors[x]] = x

# integer representation
for x in range(len(colors)):
  colors[x] = mapping[colors[x]]

one_hot_encode = to_categorical(colors)
print(one_hot_encode)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Restructure data where object types as one_hot vector. Shape from [19,4] to [19,8] 


In [173]:
print(X_test[0])#orginal

[ 8.32390594  0.         -2.22259021  0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.         28.90819359  0.98503017  0.7940141
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.        ]


In [174]:
bkg_file= '/home/aadi/praktika/ADC/files/background_for_training.h5'

In [175]:
events=100# mitme eventi peal treenida


In [176]:
# read BACKGROUND data
with h5py.File(bkg_file, 'r') as file:
    full_data = file['Particles'][:,:,:]
    np.random.shuffle(full_data)
    if events: full_data = full_data[:events,:,:]

In [177]:
event_obj_type=full_data[:,:,3]#Object types from all events
events_phis=full_data[:,:,2]#extract phis
event_obj_oh=to_categorical(event_obj_type,5)#All the object types turned to one hot
event_wo_type_phi=full_data[:,:,:2]#original events without type and phi
cos_sin=np.stack((np.cos(events_phis),np.sin(events_phis)),axis=2)#stack cos and sine oh phi
event_w_trig=np.concatenate((event_wo_type_phi[:],cos_sin[:]),axis=2)#add trig
full_data=np.concatenate((event_w_trig[:],event_obj_oh[:]),axis=2)#orig

In [179]:
full_data[0].shape

(19, 9)

In [184]:
test_size=0.2
val_size=0.2
input_shape=152

In [185]:
X_train, X_test = train_test_split(full_data, test_size=test_size, shuffle=True)
X_train, X_val = train_test_split(X_train, test_size=val_size)

In [187]:
X_train[0].shape

(19, 9)

In [180]:
event_obj_type=full_data[:,:,3]#Object types from all events
event_obj_oh=to_categorical(event_obj_type,5)#All the object types turned to one hot
event_wo_type=full_data[:,:,:3]#original events without type
full_data2=np.concatenate((event_wo_type[:],event_obj_oh[:]),axis=2)#original data combined with one hot vectors

In [182]:
full_data2[0].shape

(19, 8)

In [17]:
event_obj_type=testing[:,3]#type of elements extracted

In [36]:
len(full_data)

100

In [ ]:
import numpy as np
from tensorflow.keras.utils import to_categorical
### Categorical data to be converted to numeric data
colors = ["None", "MET", "electron", "muon", "jet"]

### Universal list of colors
total_colors = ["None", "MET", "electron", "muon", "jet"]

### map each color to an integer
mapping = {}
for x in range(len(total_colors)):
  mapping[total_colors[x]] = x

# integer representation
for x in range(len(colors)):
  colors[x] = mapping[colors[x]]

one_hot_encode = to_categorical(colors)
print(one_hot_encode)

Restructure data where object types as one_hot vector. Shape from [19,4] to [19,8] 


In [11]:
full_data[3] #original 19,4 shape

array([[39.33615494,  0.        ,  1.00352752,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [28.76571083,  1.69506621, -1.92028069,  3.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.

In [12]:
testing=full_data[99]
print(testing)

[[36.76086426  0.          0.65978301  1.        ]
 [28.77516556  2.60976386 -2.98817372  2.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [13]:
event_obj_type=testing[:,3]#type of elements extracted
#np.transpose(data_obj_type)
print(event_obj_type)

[1. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
#to onehot vector
event_obj_oh=to_categorical(event_obj_type,5)
#print(event_obj_oh)

In [20]:
event_wo_type=testing[:,:3]#event without type
#print(event_wo_type)

In [21]:
event_oh=np.concatenate((event_wo_type,event_obj_oh),axis=1)
print(event_oh.shape)
#print(event_oh)

(19, 8)


In [157]:
#suurema batchi peal
#print(full_data[:])
event_obj_type=full_data[:,:,3]
events_phis=full_data[:,:,2]
#print(event_obj_type)Object types from all events
event_obj_oh=to_categorical(event_obj_type,5)
#print(event_obj_oh[3])All the object types turned to one hot
event_wo_type_phi=full_data[:,:,:2]#original events without type and phi
cos_sin=np.stack((np.cos(events_phis),np.sin(events_phis)),axis=2)#stack cos and sine oh phi
event_w_trig=np.concatenate((event_wo_type_phi[:],cos_sin[:]),axis=2)#add trig
event_oh_trig=np.concatenate((event_w_trig[:],event_obj_oh[:]),axis=2)#add oh vectors

In [160]:
#print(cos_sin)
print(event_oh_trig[6])
#print(event)

[[ 3.79869766e+01  0.00000000e+00 -8.81660107e-01  4.71885002e-01
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 2.41772156e+01  6.17406607e-01  5.75752756e-01 -8.17623853e-01
   0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   1.00000000e+00  0.0000000

In [78]:
print(event_oh[6,:])
event=event_oh[6,:]
events_phis=event[:,2]#excract phi values
event_wo_phis=np.delete(event, obj=2,axis=1)#delete original phi
events_trig=np.insert(event_wo_phis, 2, values=np.sin(events_phis), axis=1)# add sine of phi
events_trig=np.insert(events_trig, 2, values=np.cos(events_phis), axis=1)#add cos of phi
events_trig#The order of features will be P_t, eta,cos(phi),sin(phi),types
#= np.sin(b[:,1])

[[37.98697662  0.          2.65016508  0.          1.          0.
   0.          0.        ]
 [24.17721558  0.61740661 -0.95727181  0.          0.          1.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.        ]
 [19.66394234 -2.01761365 -1.56609476  0.          0.          0.
   0.          1.        ]
 [18.11653709  1.29568124  2.2897222   0.          0.          0.
   0

array([[ 3.79869766e+01,  0.00000000e+00, -8.81660107e-01,
         4.71885002e-01,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.41772156e+01,  6.17406607e-01,  5.75752756e-01,
        -8.17623853e-01,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.000000

In [71]:
events_trig.shape

(19, 9)

In [188]:
import argparse
import h5py
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras.utils import to_categorical

def create_datasets_dense_onehot(bkg_file, output_bkg_name, signals_files, output_signal_names, events=None, test_size=0.2, val_size=0.2, input_shape=171):

    # read BACKGROUND data
    with h5py.File(bkg_file, 'r') as file:
        full_data = file['Particles'][:,:,:]
        np.random.shuffle(full_data)
        if events: full_data = full_data[:events,:,:]
    ##########################Adding OH,cos(phi),sin(phi)############################################        
    event_obj_type=full_data[:,:,3]#Object types from all events
    events_phis=full_data[:,:,2]#extract phis
    event_obj_oh=to_categorical(event_obj_type,5)#All the object types turned to one hot
    event_wo_type_phi=full_data[:,:,:2]#original events without type and phi
    cos_sin=np.stack((np.cos(events_phis),np.sin(events_phis)),axis=2)#stack cos and sine oh phi
    event_w_trig=np.concatenate((event_wo_type_phi[:],cos_sin[:]),axis=2)#add trig
    full_data=np.concatenate((event_w_trig[:],event_obj_oh[:]),axis=2)#original data combined with OH v. and trig       
    ##################################################################################################
    
    
    ####################3ONLY OH VECTOR ADDING#########################################################
    #event_obj_type=full_data[:,:,3]#Object types from all events
    #event_obj_oh=to_categorical(event_obj_type,5)#All the object types turned to one hot
    #event_wo_type=full_data[:,:,:3]#original events without type
    #full_data=np.concatenate((event_wo_type[:],event_obj_oh[:]),axis=2)#original data combined with one hot vectors
    ###################################################################################################

    # define training, test and validation datasets
    X_train, X_test = train_test_split(full_data, test_size=test_size, shuffle=True)
    X_train, X_val = train_test_split(X_train, test_size=val_size)

    del full_data

    # flatten the data for model input
    X_train = X_train.reshape(X_train.shape[0], input_shape)
    X_test = X_test.reshape(X_test.shape[0], input_shape)
    X_val = X_val.reshape(X_val.shape[0], input_shape)


    with h5py.File(output_bkg_name + '_OH_dataset.h5', 'w') as h5f:
        print("saving")
        h5f.create_dataset('X_train', data = X_train)
        h5f.create_dataset('X_test', data = X_test)
        h5f.create_dataset('X_val', data = X_val)  
        
        
    if signals_files:
        # read SIGNAL data
        for i, signal_file in enumerate(signals_files):
            print("teen if")
            f = h5py.File(signal_file,'r')
            signal_data = f['Particles'][:,:,:]
            
            
            event_obj_type=signal_data[:,:,3]#Object types from all events
            events_phis=signal_data[:,:,2]#extract phis
            event_obj_oh=to_categorical(event_obj_type,5)#All the object types turned to one hot
            event_wo_type_phi=signal_data[:,:,:2]#original events without type and phi
            cos_sin=np.stack((np.cos(events_phis),np.sin(events_phis)),axis=2)#stack cos and sine oh phi
            event_w_trig=np.concatenate((event_wo_type_phi[:],cos_sin[:]),axis=2)#add trig
            signal_data=np.concatenate((event_w_trig[:],event_obj_oh[:]),axis=2)#original data combined with OH v. and trig 
            
            
            
            
            ##same process as before turning types to onehot vectors#######################3
            #event_obj_type=signal_data[:,:,3]#Object types from all events
            #event_obj_oh=to_categorical(event_obj_type,5)#All the object types turned to one hot
            #event_wo_type=signal_data[:,:,:3]#original events without type
            #signal_data=np.concatenate((event_wo_type[:],event_obj_oh[:]),axis=2)#original data combined with one hot vectors
            ####################################################33#####
            signal_data = signal_data.reshape(signal_data.shape[0],input_shape)
            with h5py.File(output_signal_names[i] + '_OH_dataset.h5', 'w') as h5f2:
                h5f2.create_dataset('Data', data = signal_data)        
    return                                                                                

In [ ]:
sspython3 create_datasets_OH.py 
--bkg_file '/home/aadi/praktika/ADC/files/background_for_training.h5' 
--output_bkg_name 'BKG_OH_TRIG'
--signals_files '/home/aadi/praktika/ADC/files/Ato4l_lepFilter_13TeV.h5' 
--output_signal_names 'Ato4l_lepFilter_13TeV_OH' 
--events=1000000



In [189]:
signal_files = ['/home/aadi/praktika/ADC/files/Ato4l_lepFilter_13TeV.h5',
            '/home/aadi/praktika/ADC/files/hChToTauNu_13TeV_PU20.h5',
            '/home/aadi/praktika/ADC/files/hToTauTau_13TeV_PU20.h5',
            '/home/aadi/praktika/ADC/files/leptoquark_LOWMASS_lepFilter_13TeV.h5',
            '/home/aadi/praktika/ADC/files/background_for_training.h5']


In [190]:
signal_output=['./signals/oh_trig/Ato4l_lepFilter_13TeV_input_OH_trig',
                 './signals/oh_trig/hChToTauNu_13TeV_PU20_input_OH_trig',
                 './signals/oh_trig/hToTauTau_13TeV_PU20_input_OH_trig',
                 './signals/oh_trig/leptoquark_LOWMASS_lepFilter_13TeV_input_OH_trig',
                 './signals/oh_trig/background_for_training_input_OH_trig']

In [191]:
bkg_file= '/home/aadi/praktika/ADC/files/background_for_training.h5' 
output_bkg_name= './signals/oh_trig/BKG_OH_TRIG'
signals_files= signal_files 
output_signal_names= signal_output
events=4000000

In [193]:
create_datasets_dense_onehot(bkg_file, output_bkg_name, signals_files, output_signal_names, events=None, test_size=0.2, val_size=0.2, input_shape=171)

saving
teen if
teen if
teen if
teen if
teen if
